Add commands
yfakariya/review.js-vscode pull request #17
Opened 2021-06-03 16:59 UTC by fabon-f

インライン命令のdel, ins, tcyとブロック命令のblanklineを実装しました。

2021-06-29 10:48 UTC, yfakariya requested changes
すみません、完全に気付いておりませんでした……！

コントリビューションありがとうございます。1点コメントしていますので、対応または対応しないならコメントいただければと思います。

2021-06-29 10:48 UTC, yfakariya commented on lib/builder/htmlBuilder.ts
> +    block_blankline_pre(process: BuilderProcess, _node: BlockElementSyntaxTree) {
ここですが、blanklineはpre/postである必要のない命令なので、`block_blankline(...)` メソッドとして実装した方がベターかと思いますがいかがでしょう？（例として、block_noindentがあります）

`textBuilder.ts` もそうなってますし。

2021-08-04 13:54 UTC, fabon-f commented on lib/builder/htmlBuilder.ts
> +    block_blankline_pre(process: BuilderProcess, _node: BlockElementSyntaxTree) {
コメントに気付くのが遅れましたが、修正しました。

2021-08-06 15:59 UTC, yfakariya approved these changes

2021-08-06 16:00 UTC, merged

2021-08-06 16:00 UTC, yfakariya commented
ありがとうございました！